In [1]:
import pandas as pd
import numpy as np

### 1. Pandas Version

In [2]:
pd.__version__

'2.3.2'

## Fuel Dataset

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

### 2. Records count

In [4]:
# How many records are in the dataset?
df.shape

(9704, 11)

### 3. Fuel types

In [5]:
# How many fuel types are presented in the dataset?
df.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

### 4. Missing values

In [6]:
# How many columns in the dataset have missing values?
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

### 5. Max fuel efficiency

In [7]:
# What's the maximum fuel efficiency of cars from Asia?
print(f"The maximum fuel effiency of cars in Asia is: {df[df.origin == 'Asia'].fuel_efficiency_mpg.max()}")

The maximum fuel effiency of cars in Asia is: 23.759122836520497


### 6. Median Value of horsepower

In [8]:
# Find the median value of horsepower column in the dataset.
print(f'Median horsepower: {df.horsepower.median()}')


Median horsepower: 149.0


In [9]:
# Next, calculate the most frequent value of the same horsepower column.
print(f'Most frequent horsepower: {df.horsepower.mode()[0]}')

Most frequent horsepower: 152.0


In [10]:
# Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
# Now, calculate the median value of horsepower once again.
df.fillna({'horsepower': df.horsepower.mode()[0]}, inplace=True)
print(f'Median horsepower after filling nulls with most frequent horsepower: {df.horsepower.median()}')

Median horsepower after filling nulls with most frequent horsepower: 152.0


### 7. Sum of weights


In [11]:
# Select all the cars from Asia
asia_cars = df[df.origin == 'Asia']
asia_cars.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [12]:
# Select only columns vehicle_weight and model_year
asia_cars_weight_year = asia_cars[['vehicle_weight', 'model_year']]
asia_cars_weight_year

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [13]:
# Select the first 7 values
asia_cars_weight_year_7 = asia_cars_weight_year.iloc[:7]
asia_cars_weight_year_7

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [14]:
# Get the underlying NumPy array. Let's call it X.
X = np.array(asia_cars_weight_year_7)
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [15]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T@X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [16]:
# Invert XTX.
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [17]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [18]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = (XTX_inv @ X.T) @ y
w

array([0.01386421, 0.5049067 ])

In [19]:
# What's the sum of all the elements of the result?
sum_w = w.sum()
print(f'The sum of weights is: {sum_w}')


The sum of weights is: 0.5187709081074016
